FROM ruby:2.3.3

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y imagemagick ghostscript

RUN useradd -d /app -m app
RUN chown -R app /usr/local/bundle
USER app
RUN mkdir -p /app/src
WORKDIR /app/src

RUN wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz
RUN tar xvf ffmpeg-release-32bit-static.tar.xz
ENV PATH "$PATH:/app/src/ffmpeg-2.8.3-32bit-static"

COPY . /app/src
RUN bundle install

EXPOSE 5000
CMD ./exe/attache start -c web=1
